name: Bug report
description: File a bug report.
title: "[Bug] Provide a short description of the bug here"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        Provide details about the host running the container.
        Examples:
          - Operating system (e.g. Ubuntu, Windows, TrueNAS, openmediavault, unRAID, etc).
          - Version of the operating system.
          - CPU architecture (x86-64, arm, arm64, etc).
          - Model of the device, if applicable (e.g. Raspberry Pi 4B, Synology DS418, QNAP TS-364, etc).
          - The Docker version (output of `docker version`).
          - Anything else specific to your environment.  Examples:
            - Network share (NFS, CIFS) mapped to the container.
            - Docker running in LXC container.
            - etc.
          - If applicable, how the UI provided by the container is access:
            - Browser (Chrome, Firefox, Edge, etc).
            - Version of the browser.
            - OS of the browser.
            - Is the container accessed through a reverse proxy.
            - etc.
      value: |
          - OS:
          - OS version:
          - CPU:
          - Docker version:
          - Device model:
          - Browser/OS:
    validations:
      required: false
  - type: textarea
    attributes:
      label: Container creation
      description: |
        How did you create the container ?
        Examples:
          - The `docker run` command used.
          - The compose file used.
          - Screenshots of the management tool UI (e.g. Portainer, unRAID, etc) showing container settings.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Container log
      description: Please copy/paste the output of `docker logs <container name>`.
      render: text
    validations:
      required: true
  - type: textarea
    attributes:
      label: Container inspect
      description: |
        If the container is running, please provide the output of `docker inspect <container name>`.
        **Attention**: If you defined passwords, secrets or any sensitive information via environment variables, make sure to remove them from the output.
      render: text
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Anything that will give more context about the issue you are encountering.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
